import{useState,type FormEvent,type ReactNode}from'react';
type Page='dashboard'|'pending'|'addBooks'|'profile';type Kind='book'|'learning'|'discussion';type Req={id:string,k:Kind,title:string,person:string,capacity?:string,when?:string,time?:string};
const seed:Req[]=[
{id:'SLIIT-RES-B-98042',k:'book',title:'Data Structures & Algorithms',person:'Saman Perera (IT21004582)',when:'Sep 18, 9:40 AM'},
{id:'SLIIT-RES-B-98045',k:'book',title:'Information Security Principles',person:'Dilini Silva (IT21056912)',when:'Sep 18, 9:35 AM'},
{id:'SLIIT-RES-LR-98042',k:'learning',title:'Learning Room 3',person:'A.K Perera (IT21004582)',capacity:'4 People',time:'Sep 15, 15:00 PM - 17:00 PM'},
{id:'SLIIT-RES-LR-98043',k:'learning',title:'Learning Room 7',person:'Ama Devindi (IT21056912)',capacity:'5 People',time:'Sep 15, 15:00 PM - 17:00 PM'},
{id:'SLIIT-RES-LR-98044',k:'learning',title:'Learning Room 5',person:'Chirath Silva (IT21056912)',capacity:'5 People',time:'Sep 15, 13:00 PM - 15:00 PM'},
{id:'SLIIT-RES-DR-98044',k:'discussion',title:'Discussion Room 2',person:'Bhanuga Perera (LC21004582)',capacity:'8 People',time:'Sep 15, 15:00 PM - 17:00 PM'},
{id:'SLIIT-RES-DR-98045',k:'discussion',title:'Discussion Room 6',person:'Prabashwara Silva (IT21056912)',capacity:'7 People',time:'Sep 15, 13:00 PM - 15:00 PM'}];
const tabs:[Kind,string][]=[['book','Books'],['learning','Learning Space'],['discussion','Discussion Space']];
function Icon({name}:{name:string}){
const base={viewBox:'0 0 24 24',width:24,height:24,fill:'none',stroke:'currentColor',strokeWidth:2,strokeLinecap:'round' as const,strokeLinejoin:'round' as const,'aria-hidden':true as const};
if(name==='Dashboard')return <svg {...base}><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z" fill="currentColor" stroke="none"/></svg>;
if(name==='Pending')return <svg {...base}><rect x="4" y="4" width="16" height="17" rx="2" fill="currentColor" stroke="none"/><path d="M9 3v4M15 3v4M8 11h8" stroke="#112850"/></svg>;
if(name==='Add Books')return <svg {...base}><path d="M4 5a2 2 0 0 1 2-2h14v17H6a2 2 0 0 0-2 2z" fill="currentColor" stroke="none"/><path d="M4 5v17M8 7h8M8 10h8" stroke="#112850"/></svg>;
if(name==='Profile')return <svg {...base}><circle cx="12" cy="12" r="8" fill="currentColor" stroke="none"/></svg>;
const d=name==='note'?'M4 5.5A1.5 1.5 0 0 1 5.5 4h13A1.5 1.5 0 0 1 20 5.5v10a1.5 1.5 0 0 1-1.5 1.5H9l-5 4z':name==='back'?'m15 18-6-6 6-6':'M5 12h14m-6-6 6 6-6 6';
return <svg {...base}><path d={d}/></svg>
}
function App(){
const[page,setPage]=useState<Page>(()=>{const p=new URLSearchParams(location.search).get('page');return p==='pending'||p==='addBooks'||p==='profile'?p:'dashboard'}),[kind,setKind]=useState<Kind>('book'),[rows,setRows]=useState(seed),[counts,setCounts]=useState({book:12,learning:5,discussion:3}),[form,setForm]=useState<'physical'|'ebook'|'note'|null>(()=>{const f=new URLSearchParams(location.search).get('form');return f==='physical'||f==='ebook'||f==='note'?f:null}),[dialog,setDialog]=useState<{title:string,text:string,button:string,extra?:string}|null>(null),[active,setActive]=useState<{r:Req,a:'approve'|'reject'}|null>(null),[reason,setReason]=useState('There is an inconsistency in your information; therefore, we are rejecting this request.'),[decisionNote,setDecisionNote]=useState('');
const go=(p:Page)=>{setPage(p);setForm(null)},jump=(k:Kind)=>{setKind(k);go('pending')};
const finish=()=>{if(!active)return;let{r,a}=active;setRows(x=>x.filter(q=>q.id!==r.id));setCounts(x=>({...x,[r.k]:Math.max(0,x[r.k]-1)}));setActive(null);setDialog({title:a==='approve'?'Reservation Approved':'Request Rejected',text:a==='approve'?'The reservation request has been approved.':'The student will be notified of the rejection.',button:'Done',extra:a==='reject'?reason:decisionNote||undefined});setDecisionNote('')};
const bookSubmit=(e:FormEvent)=>{e.preventDefault();setForm(null);setDialog({title:form==='ebook'?'eBook Uploaded Successfully':'Book Added Successfully',text:form==='ebook'?'The digital file has been saved to the eLibrary. Students can now access and download this eBook immediately.':'The physical book has been registered in the catalog and is now available for students to reserve.',button:'Add Another / Done'})};
const noteSubmit=(e:FormEvent)=>{e.preventDefault();setForm(null);setDialog({title:'Note Sent Successfully',text:'Your note has been published and users will receive a notification shortly.',button:'Done'})};
const metric=(label:ReactNode,val:string,tone:string='orange',onClick?:()=>void)=><button className="metric" onClick={onClick}><span>{label}</span><b className={tone}>{val}</b></button>;
const field=(label:string,child:ReactNode)=><label className="field"><span>{label}</span>{child}</label>;
const upload=(label:string,accept='image/*')=><label className="upload"><span>{label}</span><span className="drop">▣<small>Drag &amp; drop or Click to upload</small><input type="file" accept={accept}/></span></label>;
return <main className="device">
<div className="status"><b>9:41</b><span className="status-icons"><svg viewBox="0 0 20 16"><path d="M1 15V11h3v4zm5 0V8h3v7zm5 0V5h3v10zm5 0V1h3v14z" fill="currentColor"/></svg><svg viewBox="0 0 19 15"><path d="M1 5.2a12 12 0 0 1 17 0L9.5 14z" fill="currentColor"/></svg><svg viewBox="0 0 27 14"><rect x=".7" y=".7" width="23" height="12.6" rx="3" fill="none" stroke="currentColor" strokeWidth="1.5"/><rect x="2.8" y="2.7" width="19" height="8.5" rx="1.5" fill="currentColor"/><path d="M25 4.5v5" stroke="currentColor" strokeWidth="1.5"/></svg></span></div>
<div className="content">
{page==='dashboard'&&<><header className="brand"><b>eLibrary<span>.SLIIT</span></b><small>The Knowledge University</small></header><h1 className="dash-title">Admin Dashboard</h1><section className="welcome"><h2>Welcome, Administrator</h2><p>eLibrary.SLIIT Management Portal</p></section><div className="metrics">
{metric(<>Pending Books<br/>Reservations</>,String(counts.book),'orange',()=>jump('book'))}{metric(<>Pending Learning Space<br/>Reservations</>,String(counts.learning),'orange',()=>jump('learning'))}{metric(<>Pending Discussion<br/>Space Reservations</>,String(counts.discussion),'orange',()=>jump('discussion'))}{metric(<>Available Learning<br/>Spaces</>,'6/8','green')}{metric(<>Available Discussion<br/>Spaces</>,'4/6','green')}{metric(<>Reserved Books :<br/>This Week</>,'28','navy',()=>jump('book'))}</div></>}
{page==='pending'&&<><h1 className="title">Pending Reservations</h1><div className="tabs">{tabs.map(([k,t])=><button className={kind===k?'sel':''} key={k} onClick={()=>setKind(k)}>{t}</button>)}</div><section className="requests">{rows.filter(r=>r.k===kind).map(r=><article className="request" key={r.id}><h2>{r.title}</h2><p>{r.k==='discussion'?'Lecturer:':'Student:'} {r.person}</p>{r.k==='book'?<p>Requested: {r.when}</p>:<><p>Capacity: {r.capacity}</p><p className="time">Reservation: {r.time}</p></>}<p>Reservation ID : <b>#{r.id}</b></p><div className="actions"><button onClick={()=>setActive({r,a:'approve'})}>Approve</button><button onClick={()=>setActive({r,a:'reject'})}>Reject</button></div></article>)}{!rows.some(r=>r.k===kind)&&<p className="empty">No pending reservations</p>}</section></>}
{page==='addBooks'&&!form&&<><h1 className="title add-title">Add Books</h1><button className="note" onClick={()=>setForm('note')}><Icon name="note"/>Click here to post a note.<Icon name="arrow"/></button><section className="type-list"><button className="type-card" onClick={()=>setForm('physical')}><img src="/assets/physical-books.jpeg"/><b>Physical Books</b><span>To the Library</span><i>→</i></button><button className="type-card" onClick={()=>setForm('ebook')}><img src="/assets/ebooks.jpeg"/><b>E-Books</b><span>To the Library Portal</span><i>→</i></button></section></>}
{page==='addBooks'&&(form==='physical'||form==='ebook')&&<form className="form" onSubmit={bookSubmit}><button type="button" className="form-head" onClick={()=>setForm(null)}>‹　Add New Book</button>{field('Book Name',<input required placeholder="e.g., Designing Data-Intensive Applications"/>)}{field('Author',<input required placeholder="e.g., Martin Kleppmann"/>)}{field('Published Date',<input required placeholder="YYYY-MM-DD"/>)}{field('Category',<select required defaultValue="Computer Science"><option>Computer Science</option><option>Management</option><option>Law</option><option>Engineering</option></select>)}{form==='physical'&&field('Bookshelf Number',<input required placeholder="e.g., CS-04-B"/>)}{upload('Upload Book Photo')}{form==='ebook'&&upload('Upload eBook File','application/pdf') }<button className="submit">Add Book</button></form>}
{page==='addBooks'&&form==='note'&&<form className="form note-form" onSubmit={noteSubmit}><button type="button" className="form-head" onClick={()=>setForm(null)}>‹　Add a Note for Publish</button>{field('Heading',<input required placeholder="e.g., Resource Update: UI/UX Design Trends"/>)}{field('Description',<textarea required placeholder="The latest edition has just been added to the eLibrary."/>) }{upload('Upload Photos')}<button className="submit">Send Note</button></form>}
{page==='profile'&&<><h1 className="title">Admin Profile</h1><section className="identity"><img src="/assets/admin-profile.jpeg"/><h2>Dr. Kumari Perera</h2><p>Senior Librarian / Library Admin</p></section><section className="details">{[['Admin ID','ADM001'],['Email Address','kumari.p@sliit.lk'],['Phone Number','+94 11 754 1130'],['Campus Branch','Malabe Main Branch']].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</section><button className="logout" onClick={()=>setDialog({title:'Log Out Account',text:'Are you sure you want to log out of the admin account?',button:'Log Out'})}>Log Out Account</button></>}
</div>
<nav className="nav">{(['dashboard','pending','addBooks','profile'] as Page[]).map((p,i)=>{let n=['Dashboard','Pending','Add Books','Profile'][i];return <button key={p} className={page===p?'active':''} onClick={()=>go(p)}><Icon name={n}/><span>{n}</span></button>})}<i className="homebar"/></nav>
{active&&<div className="veil"><section className="dialog"><i className="clock">◷</i><h2>{active.a==='reject'?'Reason for Rejection':'Approve Reservation?'}</h2>{active.a==='reject'?<textarea className="reason" value={reason} onChange={e=>setReason(e.target.value)}/>:<><p>{active.r.title} · {active.r.person}</p><textarea className="reason" placeholder="Add a note for this approval (optional)" value={decisionNote} onChange={e=>setDecisionNote(e.target.value)}/></>}<p className="rid">Reservation ID<br/><b>#{active.r.id}</b></p><button className="dialog-button" onClick={finish}>{active.a==='reject'?'Reject Request':'Approve'}</button><button className="cancel" onClick={()=>setActive(null)}>Cancel</button></section></div>}
{dialog&&<div className="veil"><section className="dialog"><i className="clock">◷</i><h2>{dialog.title}</h2><p>{dialog.text}</p>{dialog.extra&&<p className="rid">Rejection note<br/><b>{dialog.extra}</b></p>}<button className="dialog-button" onClick={()=>{let logout=dialog.title==='Log Out Account';setDialog(null);if(logout)go('dashboard')}}>{dialog.button}</button></section></div>}
</main>}
export default App